import { collectionsName } from 'src/configuration/type/firebase/firebase.type';

export const collectionNames = {
  USERS: 'users' as collectionsName,
  BETS: 'bets' as collectionsName,
  LEAGUES: 'leagues' as collectionsName,
  MATCHES: 'matches' as collectionsName,
  ODDS: 'odds' as collectionsName,
  PARTNERS: 'partners' as collectionsName,
  ADMINS: 'administrators' as collectionsName,
  TICKETS: 'tickets' as collectionsName,
  NOTIFICATIONS: 'notifications' as collectionsName,
  PREFERENCES: 'preferences' as collectionsName,
  LOGS: 'logs' as collectionsName,
  IMAGES: 'images' as collectionsName,
  COUNTRIES: 'countries' as collectionsName,
  TEAMS: 'team' as collectionsName,
  SPORTS: 'sports' as collectionsName,
  MINIGAME: 'mini_games' as collectionsName,
  BET_MINIGAME: 'bet_mini_games' as collectionsName,
  POINT_HISTORIES: 'point_histories' as collectionsName,
  EDIT_HISTORIES: 'edit_histories' as collectionsName,
  BANKBOOKS: 'bankbooks' as collectionsName,
  DOMAINS: 'domains' as collectionsName,
  CASH_HISTORIES: 'cash_histories' as collectionsName,
  ODD_TYPES: 'odd_types' as collectionsName,
  SETTLEMENTS: 'settlements' as collectionsName,
  VIRTUAL_GAME: 'virtual_game' as collectionsName,
};
