export type collectionsName =
    | 'users'
    | 'predictions'
    | 'products'
    | 'point_histories'
    | 'cash_histories'
    | 'bets_market'
    | 'bets_dice'
    | 'bets'
    | 'chainlink'
    | 'charts'
    | 'preferences'
    | 'markets'
    | 'dices'
    | 'leaderboard'
    | 'statistics'
    | 'manipulations'
    | 'bot_preferences';
